import { registerEnumType } from '@nestjs/graphql';

// SQLite stores status as a plain string, so the enum is defined here in the
// app layer (single source of truth) rather than generated by Prisma.
export enum ApplicationStatus {
  PENDING = 'PENDING',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEWED = 'INTERVIEWED',
  HIRED = 'HIRED',
  REJECTED = 'REJECTED',
  AUTO_DELETE = 'AUTO_DELETE',
}

registerEnumType(ApplicationStatus, {
  name: 'ApplicationStatus',
  description: 'The stage of a job application in the hiring pipeline.',
});
