import { registerEnumType } from '@nestjs/graphql';

// SQLite stores job type as a plain string, so the enum is defined here in the
// app layer (single source of truth) rather than generated by Prisma.
export enum JobType {
  INTERNSHIP = 'INTERNSHIP',
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
}

registerEnumType(JobType, {
  name: 'JobType',
  description: 'The employment type for a job application.',
});
